### ISSUE TITLE
Make a minimal build of VTK available on rwinlib

### ISSUE THREAD

**Issue by astamm** [astamm/riot#3]
For making the package available and easily installable on Windows, it would be ideal to have a minimal build of VTK (i.e. with I/O capabilities) included in the list of softs on `rwinlib`. @jeroen would you be ok with this? how can I contribute it? I already have headers and libs for `i386`, `x64` and `x64-ucrt`.

**Comment by jeroen** [comment]
You would submit a pull request to https://github.com/r-windows/rtools-packages
From there we can build copy binaries to rwinlib

**Comment by astamm** [comment]
Thanks. In preparing the `PKGBUILD` file, is there a way to test that it is working properly before sending the PR out? I am new to this procedure.

**Comment by jeroen** [comment]
You have to install rtools4 and run `makepkg-mingw` in the directory with the PKGBUILD

**Comment by astamm** [comment]
Sorry I was not clear in what I asked. I figured that out once I am on windows machine but I am a macOS user. I was wondering if there is a windows platform that you would know of on to which I can run test before submitting the PR.

**Comment by jeroen** [comment]
Ah no I don't, you can just submit the PR and hope for the best :)
