### ISSUE TITLE
Linking with vtkpugixml

### ISSUE THREAD

**Issue by astamm** [astamm/riot#7]
When testing on the win-builder machines, they complain upon linking (both release and devel):
```
g++ -shared -s -static-libgcc -o riot.dll tmp.def RcppExports.o fascicleReaders.o fascicleWriters.o tinyxml2.o -L../windows/vtk-9.2.2-1/lib-10.4.0/x64 -L../windows/vtk-9.2.2-1/lib/x64 -lvtkIOXML -lvtkIOXMLParser -lvtkIOCore -lvtkIOLegacy -lvtkCommonExecutionModel -lvtkCommonDataModel -lvtkCommonTransforms -lvtkCommonMath -lvtkCommonMisc -lvtkCommonSystem -lvtkCommonCore -lvtkdoubleconversion -lvtkexpat -lvtklz4 -lvtklzma -lvtkpugixml -lvtksys -lvtkzlib -lgdi32 -Ld:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64 -Ld:/rtools42/x86_64-w64-mingw32.static.posix/lib -LD:/RCompile/recent/R/bin/x64 -lR
D:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lvtkpugixml
```
that it does not find `-lvtkpugixml`. But it is there in the `rwinlib/vtk` .
@jeroen: do I have to also contribute a PKGBUILD file somewhere in Rtools42 as well?

**Comment by jeroen** [comment]
I think you need to update the version here to 9.2.2: https://github.com/astamm/riot/blob/master/src/Makevars.win#L1

**Comment by astamm** [comment]
Oh I dis that already on my local copy not yet pushed on GitHub.

**Comment by astamm** [comment]
But it still throw the same error on win builder

**Comment by jeroen** [comment]
Can you show me the winbuilder log then?

**Comment by astamm** [comment]
Sure sorry, here it is <https://win-builder.r-project.org/RT4aZRhlDL8U/>

**Comment by jeroen** [comment]
I don't see any `libvtkpugixml.a` in https://github.com/rwinlib/vtk. Perhaps this plugin is not part of the Windows build.  I think you should remove that flag from your `Makevars.win`.

**Comment by astamm** [comment]
It seems to be there: https://github.com/rwinlib/vtk/tree/master/lib/x64/lib

**Comment by astamm** [comment]
Apparently libs at location you provide are still for `v9.0.1` while libs related to `9.2.2` have been copied into `vtk/lib/x64/lib` for a reason I don't know.

**Comment by jeroen** [comment]
OK maybe I messed up. I tried again, I think it looks good now: https://github.com/rwinlib/vtk/releases/tag/v9.2.2

**Comment by astamm** [comment]
Works perfectly. Thanks!
